# Generated by Django 2.2.3 on 2020-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shangpin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('catagory', models.IntegerField(choices=[(1, '动漫'), (2, '历史'), (3, '剧情')])),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
