# Generated by Django 2.2.3 on 2020-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_shangpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangpin',
            name='catagory',
            field=models.IntegerField(choices=[(1, '吃的'), (2, '喝的'), (3, '玩的')]),
        ),
    ]
