# Generated by Django 2.2.3 on 2020-07-24 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200715_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('sum_price', models.CharField(blank=True, max_length=20, null=True)),
                ('goods', models.ManyToManyField(blank=True, related_name='good', to='app1.Shangpin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Dingdan',
        ),
    ]
