# Generated by Django 2.2.3 on 2020-07-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200724_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
