# Generated by Django 2.2.3 on 2020-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order_statues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statues',
            field=models.IntegerField(choices=[(1, '未付款'), (2, '已付款'), (3, '已撤销')], default=1),
        ),
    ]
